environment: production
chdir: /home/jade/eligant_production/current/
address: 93.189.40.170
user: acoplet
group: acoplet
port: 8080
pid: /home/jade/eligant_production/current/tmp/thin.pid
rackup: /home/jade/eligant_production/current/config.ru
log: /home/jade/eligant_production/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true